### PR TITLE
Add mapping for tanmay3011 to Tanmay Sinha

### PR DESCRIPTION
**Pull request by tanmay3011**

### CODE REVIEW

**Comment by fxn** [comment]
Could you please add coverage? See https://github.com/fxn/rails-contributors/blob/master/test/credits/canonical_names_test.rb.

**Comment by tanmay3011** [comment]
@fxn  Added

**Comment by fxn** [comment]
Excellent, I'll deploy tomorow.

**Comment by tanmay3011** [comment]
@fxn Is it deployed?

**Comment by fxn** [comment]
There you go http://contributors.rubyonrails.org/contributors/tanmay-sinha/commits, thanks!

**Comment by tanmay3011** [comment]
Thanks! You rock! :+1:

**Pull request merged**
