### PR TITLE
Yuuji Yaginuma and Yuji Yaginuma are same contributor

### PR DESCRIPTION
**Pull request by koic**
This PR will bring together the name of [y-yagi](https://github.com/y-yagi).

### CODE REVIEW

**Comment by fxn** [comment]
Hey, I have some weird networking issue with this project's VM, I'll deploy as soon as I fix it.

**Comment by koic** [comment]
I got it. Thank you for letting me know.

**Comment by fxn** [comment]
In production http://contributors.rubyonrails.org/contributors/yuuji-yaginuma/commits, thanks @koic!

**Comment by koic** [comment]
@fxn I confirmed that. Thank you!

**Pull request merged**
