### PR TITLE
defines an alias for Prakash Laxkar

### PR DESCRIPTION
**Pull request by prakashlaxkar**

### CODE REVIEW

**Comment by fxn** [comment]
Hi! Would you mind using single quotes also for the alias?

**Comment by prakashlaxkar** [comment]
@fxn pr updated. Thanks

**Comment by fxn** [comment]
Thanks! It won't be instant, on my mobile and need to deploy, but will be soon in production.

**Comment by fxn** [comment]
In production http://contributors.rubyonrails.org/contributors/prakash-laxkar/commits.

**Pull request merged**
