### PR TITLE
defines an alias for Arvind Mehra

### PR DESCRIPTION
**Pull request by amitsuroliya**

### CODE REVIEW

**Comment by fxn** [comment]
Hi! In that file tests are sorted by alias... could you please move it?

**Comment by amitsuroliya** [comment]
Done @fxn. Please review. Thanks.

**Comment by fxn** [comment]
There you go http://contributors.rubyonrails.org/contributors/arvind-mehra/commits, thanks!

**Comment by amitsuroliya** [comment]
Thanks :heart:

**Pull request merged**
