### PR TITLE
Upgrade to Rails 5

### PR DESCRIPTION
**Pull request by danieldimitrov**
Hey @fxn!

This is kickoff for Rails 5 upgrade. Everything what I did is based on official guides - http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0.

If you have any ideas which we should implement during this upgrade or any comments related to my code then let me know.

Have a great day!

Daniel

### CODE REVIEW

**Comment by fxn** [comment]
ACK! I have a busy week, but I'll try to look at it soon.

**Comment by danieldimitrov** [comment]
No problem, same here 😄 . Thank you in advance!

**Comment by fxn** [comment]
Awesome job!

**Comment by fxn** [comment]
I worked a little bit more on your patch (see later commits in https://github.com/fxn/rails-contributors/commits/master), and this is now deployed to production. Thanks again! ❤️

**Comment by danieldimitrov** [comment]
Thank you for your help! Also sorry for missing configs/initializers and for that belongs_to association. I completely overlooked that. 😕

**Pull request merged**
