### PR TITLE
Add credits to Sadman Khan

### PR DESCRIPTION
**Pull request by repinel**
Based on https://github.com/rails/rails/commit/319baed48e5ddb6556bcb3a89914dabf87171995

/cc @sh6khan

### CODE REVIEW

**Comment by fxn** [comment]
I'll have a look. Does the test suite pass?

**Comment by repinel** [comment]
It does. Thanks for the awesome work :smiley:

**Comment by fxn** [comment]
There you go! http://contributors.rubyonrails.org/contributors/sadman-khan/commits.

**Comment by sh6khan** [comment]
Thanks ! :D

On Tue, May 26, 2015 at 3:42 PM, Xavier Noria <notifications@github.com>
wrote:

> There you go!
> http://contributors.rubyonrails.org/contributors/sadman-khan/commits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fxn/rails-contributors/pull/66#issuecomment-105644694>
> .
>



-- 
Sadman Khan
sadman.khan999@gmail.com

**Comment by repinel** [comment]
:+1:

**Pull request merged**
