### PR TITLE
managing my credits

### PR DESCRIPTION
**Pull request by karanarora**

### CODE REVIEW

**Comment by fxn** [comment]
The test should go before the one for "Karel Minarik" if I am not mistaken.

**Comment by karanarora** [comment]
correct! sorted names in canonical_names.rb too.

**Comment by fxn** [comment]
Wow, that's what I call going beyond the call of duty :), thanks a lot!

**Comment by fxn** [comment]
In production http://contributors.rubyonrails.org/contributors/karan-arora/commits.

**Comment by karanarora** [comment]
looks good! thanks.

**Pull request merged**
